swagger: "2.0"
info:
  title: Open Api Specification Demo
  description: This is a demo yml file for documenting a our Demo REST API.
  version: 1.0.0
host: localhost:8080
basePath: /user
tags:
- name: "user"
  description: "user operations"
schemes:
  - https
paths:
  /user/add:
    post:
      tags:
      - "user"
      summary: adds a user to the databse.
      description: adds a user to the h2 database, note that restarting the api will wipe the whole database.
      parameters:
      - in: "body"
        name: "body"
        description: "user object that needs to be added to the h2 database"
        required: true
        schema:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            id:
              type: integer
            phonenumber:
              type: string
            email:
              type: string
            address:
              type: string
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: OK 
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
  /user/delete/{id}:
    delete:
      tags:
      - "user"    
      summary: delets  a user from the database.
      description: deletes a user from the h2 database, note that restarting the api will wipe the whole database.
      parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: The user ID.
      responses:
        200:
          description: OK 
  /user/get/{id}:
    get:
      tags:
      - "user"    
      summary: gets a user from the database.
      description: gets a user from the h2 database by providing it's id, note that restarting the api will wipe the whole database.
      parameters:
      - in: path
        name: id
        type: integer
        required: true
        description: The user ID.
      produces:
      - "application/json"        
      responses:
        200:
          description: OK
  /user/findAll:
    get:
      tags:
      - "user"    
      summary: gets a user from the database.
      description: gets a user from the h2 database by providing it's id, note that restarting the api will wipe the whole database.
      produces:
      - "application/json"      
      responses:
        200:
          description: OK          
          

          
 